proyectoBuzon/Models/Quejas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace proyectoBuzon.Models
{
    public partial class Quejas
    {
        public Quejas()
        {
            Respuestasqueja = new HashSet<Respuestasqueja>();
        }

        public int IdQ { get; set; }
        public int IdCl { get; set; }
        public int IdTipoq { get; set; }
        public int IdPolitica { get; set; }
        public int IdPedido { get; set; }
        public int IdEstado { get; set; }
        
        [Required]
        [StringLength(100)]
        public string DescripcionQ { get; set; }
        public DateTime? FechaQ { get; set; }

        public TblCliente IdClNavigation { get; set; }
        public Estado IdEstadoNavigation { get; set; }
        public Pedido IdPedidoNavigation { get; set; }
        public Politicas IdPoliticaNavigation { get; set; }
        public Tipoqueja IdTipoqNavigation { get; set; }
        public ICollection<Respuestasqueja> Respuestasqueja { get; set; }
    }
}

proyectoBuzon/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoBuzon4.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

proyectoBuzon/Controllers/QuejasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoBuzon.Models;

namespace proyectoBuzon.Controllers
{
    public class QuejasController : Controller
    {
        private readonly proyectoBuzonContext _context;

        public QuejasController(proyectoBuzonContext context)
        {
            _context = context;
        }

        // GET: Quejas
        public async Task<IActionResult> Index()
        {
            var proyectoBuzonContext = _context.Quejas.Include(q => q.IdClNavigation).Include(q => q.IdEstadoNavigation).Include(q => q.IdPedidoNavigation).Include(q => q.IdPoliticaNavigation).Include(q => q.IdTipoqNavigation);
            return View(await proyectoBuzonContext.ToListAsync());
        }


        public async Task<IActionResult> IndexRespuesta(int id)
        {
            // var proyectoBuzonContext = _context.Respuestasqueja.Include(r => r.IdQNavigation);
            var proyectoBuzonContext = _context.Respuestasqueja
                .Where(r => r.IdQ == id)
                .Include(r => r.IdQNavigation);
            return View(await proyectoBuzonContext.ToListAsync());
        }
        public async Task<IActionResult> IndexPendientes(int id = 1, int c=1)
        {
            var proyectoBuzonContext = _context.Quejas
                .Where(q => q.IdEstado == id)
                .Where(q => q.IdCl == c)
                .Include(q => q.IdClNavigation).Include(q => q.IdEstadoNavigation).Include(q => q.IdPedidoNavigation).Include(q => q.IdPoliticaNavigation).Include(q => q.IdTipoqNavigation);

            return View(await proyectoBuzonContext.ToListAsync());
        }


        public async Task<IActionResult> IndexSolucionadas(int id = 2, int c = 1)
        {
            var proyectoBuzonContext = _context.Quejas
                .Where(q => q.IdEstado == id)
                    .Where(q => q.IdCl == c)
                .Include(q => q.IdClNavigation).Include(q => q.IdEstadoNavigation).Include(q => q.IdPedidoNavigation).Include(q => q.IdPoliticaNavigation).Include(q => q.IdTipoqNavigation);

            return View(await proyectoBuzonContext.ToListAsync());
        }

        public IActionResult Pendysol()
        {
            return View();
        }

        public async Task<IActionResult> listarEstado(int id)
        {
            var proyectoBuzonContext = _context.Quejas.Where(q => q.IdEstado == id)
                .Include(q => q.IdClNavigation).Include(q => q.IdEstadoNavigation).Include(q => q.IdPedidoNavigation).Include(q => q.IdPoliticaNavigation).Include(q => q.IdTipoqNavigation);

            // consultar datos de la Queja

            var estado = _context.Estado.Find(id);
            ViewData["estado"] = estado;


            return View(await proyectoBuzonContext.ToListAsync());
        }


        // GET: Quejas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejas = await _context.Quejas
                .Include(q => q.IdClNavigation)
                .Include(q => q.IdEstadoNavigation)
                .Include(q => q.IdPedidoNavigation)
                .Include(q => q.IdPoliticaNavigation)
                .Include(q => q.IdTipoqNavigation)
                .FirstOrDefaultAsync(m => m.IdQ == id);
            if (quejas == null)
            {
                return NotFound();
            }

            return View(quejas);
        }

        // GET: Quejas/Create
        public IActionResult Create()
        {
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "NombresCl");
            ViewData["IdEstado"] = new SelectList(_context.Estado, "IdEstado", "NomEstado");
            ViewData["IdPedido"] = new SelectList(_context.Pedido, "IdPedido", "IdPedido");
            ViewData["IdPolitica"] = new SelectList(_context.Politicas, "IdPolitica", "NomPolitica");
            ViewData["IdTipoq"] = new SelectList(_context.Tipoqueja, "IdTipoq", "NombreTipoq");
            return View();
        }

        // POST: Quejas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdQ,IdCl,IdTipoq,IdPolitica,IdPedido,IdEstado,DescripcionQ,FechaQ")] Quejas quejas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(quejas);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl", quejas.IdCl);
            ViewData["IdEstado"] = new SelectList(_context.Estado, "IdEstado", "NomEstado", quejas.IdEstado);
            ViewData["IdPedido"] = new SelectList(_context.Pedido, "IdPedido", "IdPedido", quejas.IdPedido);
            ViewData["IdPolitica"] = new SelectList(_context.Politicas, "IdPolitica", "NomPolitica", quejas.IdPolitica);
            ViewData["IdTipoq"] = new SelectList(_context.Tipoqueja, "IdTipoq", "NombreTipoq", quejas.IdTipoq);
            return RedirectToActionPreserveMethod("indexPendientes", "Quejas");
        }

        // GET: Quejas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejas = await _context.Quejas.FindAsync(id);
            if (quejas == null)
            {
                return NotFound();
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "NombresCl", quejas.IdCl);
            ViewData["IdEstado"] = new SelectList(_context.Estado, "IdEstado", "NomEstado", quejas.IdEstado);
            ViewData["IdPedido"] = new SelectList(_context.Pedido, "IdPedido", "IdPedido", quejas.IdPedido);
            ViewData["IdPolitica"] = new SelectList(_context.Politicas, "IdPolitica", "NomPolitica", quejas.IdPolitica);
            ViewData["IdTipoq"] = new SelectList(_context.Tipoqueja, "IdTipoq", "NombreTipoq", quejas.IdTipoq);
            return View(quejas);
        }

        // POST: Quejas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdQ,IdCl,IdTipoq,IdPolitica,IdPedido,IdEstado,DescripcionQ,FechaQ")] Quejas quejas)
        {
            if (id != quejas.IdQ)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(quejas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!QuejasExists(quejas.IdQ))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl", quejas.IdCl);
            ViewData["IdEstado"] = new SelectList(_context.Estado, "IdEstado", "NomEstado", quejas.IdEstado);
            ViewData["IdPedido"] = new SelectList(_context.Pedido, "IdPedido", "IdPedido", quejas.IdPedido);
            ViewData["IdPolitica"] = new SelectList(_context.Politicas, "IdPolitica", "NomPolitica", quejas.IdPolitica);
            ViewData["IdTipoq"] = new SelectList(_context.Tipoqueja, "IdTipoq", "NombreTipoq", quejas.IdTipoq);
            return RedirectToActionPreserveMethod("indexPendientes", "Quejas");
            //return View(quejas);
        }

        // GET: Quejas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var quejas = await _context.Quejas
                .Include(q => q.IdClNavigation)
                .Include(q => q.IdEstadoNavigation)
                .Include(q => q.IdPedidoNavigation)
                .Include(q => q.IdPoliticaNavigation)
                .Include(q => q.IdTipoqNavigation)
                .FirstOrDefaultAsync(m => m.IdQ == id);
            if (quejas == null)
            {
                return NotFound();
            }

            return View(quejas);
        }

        // POST: Quejas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var quejas = await _context.Quejas.FindAsync(id);
            _context.Quejas.Remove(quejas);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToActionPreserveMethod("indexPendientes", "Quejas");
        }

        private bool QuejasExists(int id)
        {
            return _context.Quejas.Any(e => e.IdQ == id);
        }
    }
}

proyectoBuzon/Controllers/TipoquejasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoBuzon.Models;

namespace proyectoBuzon.Controllers
{
    public class TipoquejasController : Controller
    {
        private readonly proyectoBuzonContext _context;

        public TipoquejasController(proyectoBuzonContext context)
        {
            _context = context;
        }

        // GET: Tipoquejas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Tipoqueja.ToListAsync());
        }

        // GET: Tipoquejas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoqueja = await _context.Tipoqueja
                .FirstOrDefaultAsync(m => m.IdTipoq == id);
            if (tipoqueja == null)
            {
                return NotFound();
            }

            return View(tipoqueja);
        }

        // GET: Tipoquejas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tipoquejas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTipoq,NombreTipoq")] Tipoqueja tipoqueja)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoqueja);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoqueja);
        }

        // GET: Tipoquejas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoqueja = await _context.Tipoqueja.FindAsync(id);
            if (tipoqueja == null)
            {
                return NotFound();
            }
            return View(tipoqueja);
        }

        // POST: Tipoquejas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTipoq,NombreTipoq")] Tipoqueja tipoqueja)
        {
            if (id != tipoqueja.IdTipoq)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoqueja);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoquejaExists(tipoqueja.IdTipoq))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoqueja);
        }

        // GET: Tipoquejas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tipoqueja = await _context.Tipoqueja
                .FirstOrDefaultAsync(m => m.IdTipoq == id);
            if (tipoqueja == null)
            {
                return NotFound();
            }

            return View(tipoqueja);
        }

        // POST: Tipoquejas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tipoqueja = await _context.Tipoqueja.FindAsync(id);
            _context.Tipoqueja.Remove(tipoqueja);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoquejaExists(int id)
        {
            return _context.Tipoqueja.Any(e => e.IdTipoq == id);
        }
    }
}

proyectoBuzon/Views/Quejas/Create.cshtml
@model proyectoBuzon.Models.Quejas

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/Estilos/Descripcion.css">
<center>
    <h2>
        Verificar mis Quejas
    </h2>
    <p>

        @Html.ActionLink("PENDIENTES", "IndexPendientes", "Quejas", null, new { @class = "btn btn-success " })

        @Html.ActionLink("REVISADAS", "IndexSolucionadas", "Quejas", null, new { @class = "btn btn-danger" })
    </p>
</center>
<hr>
<center>
    <h3>Crea tu Queja Aquí...!!</h3>
</center>
<center>
    <hr>
    <a class="btn btn-info" asp-controller="Cliente" asp-action="Index">Regresar</a><br>

    <div class="col-md-4">

    </div>
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="IdCl" class="control-label">Nombre</label>
                    <select asp-for="IdCl" class="form-control" asp-items="ViewBag.IdCl"></select>
                </div>
                <div class="form-group">
                    <label asp-for="IdTipoq" class="control-label">Tipo de Queja</label>
                    <select asp-for="IdTipoq" class="form-control" asp-items="ViewBag.IdTipoq"></select>
                </div>
                <div class="form-group">
                    <label asp-for="IdPolitica" class="control-label">Política</label>
                    <select asp-for="IdPolitica" class="form-control" asp-items="ViewBag.IdPolitica"></select>
                </div>
                <div class="form-group">
                    <label asp-for="IdPedido" class="control-label">Pedido</label>
                    <select asp-for="IdPedido" class="form-control" asp-items="ViewBag.IdPedido"></select>
                </div>
                <div class="form-group" hidden="hidden">
                    <label asp-for="IdEstado" class="control-label"></label>
                    <select asp-for="IdEstado" class="form-control" asp-items="ViewBag.IdEstado"></select>
                </div>
                <div class="form-group">
                    <label asp-for="DescripcionQ" class="control-label">Descripción</label>
                    <input asp-for="DescripcionQ" class="form-control" />
                    <span asp-validation-for="DescripcionQ" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="CREAR" class="btn btn-default" />
                </div>
            </form>
        </div>
    </div>
    <hr>

</center>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

proyectoBuzon/Views/Quejas/Index.cshtml
@model IEnumerable<proyectoBuzon.Models.Quejas>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}
<CENTER>
    <h2>LISTAR QUEJAS</h2>
</CENTER>
<p>
    @*<a class="btn btn-info" asp-action="Create">Crear Nuevo</a>*@
    <a class="btn btn-success" asp-controller="Tipoquejas" asp-action="Index">Tipo de Queja</a>
</p>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DescripcionQ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaQ)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdClNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdEstadoNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdPedidoNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdPoliticaNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdTipoqNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DescripcionQ)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaQ)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdClNavigation.NombresCl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEstadoNavigation.NomEstado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPedidoNavigation.IdPedido)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPoliticaNavigation.NomPolitica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdTipoqNavigation.NombreTipoq)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdQ">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.IdQ">Detalle</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdQ">Elminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

proyectoBuzon/Views/Quejas/IndexPendientes.cshtml
@model IEnumerable<proyectoBuzon.Models.Quejas>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}

@*<h2>Index</h2>*@
<h2> </h2>

@*<p>
        <a asp-action="Create">Realizar nueva Queja</a>
    </p>*@


<center>
    <h2>QUEJAS PENDIENTES</h2>
</center>
@*<td>
    @Html.ActionLink("MENU PRINCIPAL", "", "Cliente", null, new { @class = "btn btn-success" })
</td>*@
<td>
    @Html.ActionLink("<< ATRAS", "Create", "Quejas", null, new { @class = "btn btn-success " })
</td>


<table class="table">
    <thead>
        <tr>
            <th>
                FECHA
            </th>
            <th>
                CLIENTE
            </th>
            <th>
                ESTADO
            </th>
            <th>
                PEDIDO
            </th>
            <th>
                TIPO DE QUEJA
            </th>
            <th>
                POLÍTICA
            </th>
            <th>
                DESCRIPCIÓN
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaQ)

                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.IdClNavigation.NombresCl)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEstadoNavigation.NomEstado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPedidoNavigation.IdPedido)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdTipoqNavigation.NombreTipoq)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPoliticaNavigation.NomPolitica)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescripcionQ)
                </td>
                <td></td>
                <td>
                    <a class="btn btn-info"asp-action="Edit" asp-route-id="@item.IdQ">Editar</a>
                    @*<a asp-action="Details" asp-route-id="@item.IdQ">Details</a> |*@
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.IdQ">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

proyectoBuzon/Views/Quejas/IndexRespuesta.cshtml
@model IEnumerable<proyectoBuzon.Models.Respuestasqueja>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}

@*<h2>Index</h2>*@
<td>
    @Html.ActionLink("<< ATRAS", "IndexSolucionadas", "Quejas", null, new { @class = "btn btn-success btn-lg" })
</td>
@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                RESPUESTAS
            </th>
          
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DescResp)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.IdQNavigation.DescripcionQ)
            </td>*@
            @*<td>
                <a asp-action="Edit" asp-route-id="@item.IdRespuestaq">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.IdRespuestaq">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.IdRespuestaq">Delete</a>
            </td>*@
        </tr>
}
    </tbody>
</table>

proyectoBuzon/Views/Quejas/IndexSolucionadas.cshtml
@model IEnumerable<proyectoBuzon.Models.Quejas>

@{
    ViewData["Title"] = "QUEJAS";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
    //   Layout = "~/Views/Shared/_Layout_Cliente.cshtml";

}
<CENTER>
    <h2>QUEJAS REVISADAS</h2>
</CENTER>
@*<p>
        <a asp-action="Create">Create New</a>

    </p>*@
@*<td>
        @Html.ActionLink("MENU PRINCIPAL","", "Cliente", null, new { @class = "btn btn-success btn-lg" })
    </td>*@

<link rel="stylesheet" href="https://maxcdn.boostrapcdn.com/boostrap/3.3.1/css/boostrap.min.css">

<div class="container">
    <div class="table-responsive">
        
            @Html.ActionLink("<< ATRAS", "Create", "Quejas", null, new { @class = "btn btn-success " })
        
        <table class="table table-striped table-bordered table-hover ">
            <thead>
                <tr class="info">
                    <th>
                        PEDIDO
                    </th>

                    <th>
                        CLIENTE
                    </th>
                    <th>
                        ESTADO
                    </th>

                    <th>
                        TIPO DE QUEJA
                    </th>
                    <th>
                        POLÍTICA
                    </th>
                    <th>
                        DESCRIPCIÓN
                    </th>
                    <th>
                        FECHA
                    </th>
                    <th>OPCIÓN</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdPedidoNavigation.IdPedido)
                        </td>
                        <td>

                            @Html.DisplayFor(modelItem => item.IdClNavigation.NombresCl)
                        </td>


                        <td>
                            @Html.DisplayFor(modelItem => item.IdEstadoNavigation.NomEstado)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.IdTipoqNavigation.NombreTipoq)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdPoliticaNavigation.NomPolitica)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DescripcionQ)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaQ)

                        </td>
                        <td> <a CLASS="btn btn-warning btn-sm" asp-action="IndexRespuesta" asp-route-id="@item.IdQ">Respuestas</a></td>
                        @*<td>
                           
                            @*<a asp-action="Details" asp-route-id="@item.IdQ">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.IdQ">Delete</a>*@
                        @*</td>*@*
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>