proyectoBuzon/Models/Sugerencias.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace proyectoBuzon.Models
{
    public partial class Sugerencias
    {
        public int IdS { get; set; }
        public int IdCl { get; set; }
        [Display(Name = "Descripción")]
        [Required]
        [StringLength(100)]
        public string DescripcionS { get; set; }
        [Display(Name = "Fecha de Sugerencia")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Required]
        public DateTime FechaS { get; set; }
        public int IdTiposug { get; set; }

        public TblCliente IdClNavigation { get; set; }
        public Tiposugerencia IdTiposugNavigation { get; set; }
    }
}

proyectoBuzon/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoBuzon4.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

proyectoBuzon/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ProyectoBuzon4.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cliente/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Cliente/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cliente/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cliente/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cliente/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

proyectoBuzon/Controllers/SugerenciasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proyectoBuzon.Models;

namespace proyectoBuzon.Controllers
{
    public class SugerenciasController : Controller
    {
        private readonly proyectoBuzonContext _context;

        public SugerenciasController(proyectoBuzonContext context)
        {
            _context = context;
        }

        // GET: Sugerencias
        public async Task<IActionResult> Index(int c = 1)
        {
            var proyectoBuzonContext = _context.Sugerencias
                .Where(s => s.IdCl == c)
                .Include(s => s.IdClNavigation).Include(s => s.IdTiposugNavigation);
            return View(await proyectoBuzonContext.ToListAsync());
        }
        public async Task<IActionResult> IndexAdmin()
        {
            var proyectoBuzonContext = _context.Sugerencias.Include(s => s.IdClNavigation).Include(s => s.IdTiposugNavigation);
            return View(await proyectoBuzonContext.ToListAsync());
        }

        // GET: Sugerencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sugerencias = await _context.Sugerencias
                .Include(s => s.IdClNavigation)
                .Include(s => s.IdTiposugNavigation)
                .FirstOrDefaultAsync(m => m.IdS == id);
            if (sugerencias == null)
            {
                return NotFound();
            }

            return View(sugerencias);
        }

        // GET: Sugerencias/Create
        public IActionResult Create()
        {
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl");
            ViewData["IdTiposug"] = new SelectList(_context.Tiposugerencia, "IdTiposug", "NombreTipoq");
            return View();
        }

        // POST: Sugerencias/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdS,IdCl,DescripcionS,FechaS,IdTiposug")] Sugerencias sugerencias)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sugerencias);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl", sugerencias.IdCl);
            ViewData["IdTiposug"] = new SelectList(_context.Tiposugerencia, "IdTiposug", "NombreTipoq", sugerencias.IdTiposug);
            return View(sugerencias);
        }

        // GET: Sugerencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sugerencias = await _context.Sugerencias.FindAsync(id);
            if (sugerencias == null)
            {
                return NotFound();
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl", sugerencias.IdCl);
            ViewData["IdTiposug"] = new SelectList(_context.Tiposugerencia, "IdTiposug", "NombreTipoq", sugerencias.IdTiposug);
            return View(sugerencias);
        }

        // POST: Sugerencias/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdS,IdCl,DescripcionS,FechaS,IdTiposug")] Sugerencias sugerencias)
        {
            if (id != sugerencias.IdS)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sugerencias);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SugerenciasExists(sugerencias.IdS))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCl"] = new SelectList(_context.TblCliente, "IdCl", "ApellidosCl", sugerencias.IdCl);
            ViewData["IdTiposug"] = new SelectList(_context.Tiposugerencia, "IdTiposug", "NombreTipoq", sugerencias.IdTiposug);
            return View(sugerencias);
        }

        // GET: Sugerencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sugerencias = await _context.Sugerencias
                .Include(s => s.IdClNavigation)
                .Include(s => s.IdTiposugNavigation)
                .FirstOrDefaultAsync(m => m.IdS == id);
            if (sugerencias == null)
            {
                return NotFound();
            }

            return View(sugerencias);
        }

        // POST: Sugerencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sugerencias = await _context.Sugerencias.FindAsync(id);
            _context.Sugerencias.Remove(sugerencias);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SugerenciasExists(int id)
        {
            return _context.Sugerencias.Any(e => e.IdS == id);
        }
    }
}

proyectoBuzon/Views/Sugerencias/Create.cshtml
@model proyectoBuzon.Models.Sugerencias

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}
<link rel="stylesheet" type="text/css" href="~/Estilos/Descripcion.css">
<center>
    <h2>Crea tu Sugerencia Aquí...!!</h2>
</center>
<hr />
<center>
    <p>

        <a class="btn btn-info" asp-controller="Cliente" asp-action="Index"><<==Regresar</a>
        @Html.ActionLink("VER SUGERENCIAS", "Index", "Sugerencias", null, new { @class = "btn btn-success " })
    </p>
   
</center>
<div class="col-md-4"></div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdCl" class="control-label">Nombre</label>
                <select asp-for="IdCl" class="form-control" asp-items="ViewBag.IdCl"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdTiposug" class="control-label">Tipo de Sugerencia</label>
                <select asp-for="IdTiposug" class="form-control" asp-items="ViewBag.IdTiposug"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaS" class="control-label">Fecha</label>
                <input asp-for="FechaS" class="form-control" />
                <span asp-validation-for="FechaS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionS" class="control-label">Descripción</label>
                <input asp-for="DescripcionS" class="form-control" />
                <span asp-validation-for="DescripcionS" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

proyectoBuzon/Views/Sugerencias/Delete.cshtml
@model proyectoBuzon.Models.Sugerencias

@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}

<h2>Eliminar</h2>

<h3>ESTAS SEGURO DE ELIMINAR ?</h3>
<div>
    <h4>Sugerencias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           DETALLE DE SUGERENCIA
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescripcionS)
        </dd>
        <dt>
           FECHA
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaS)
        </dd>
        <dt>
           CLIENTE
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdClNavigation.ApellidosCl)
        </dd>
        <dt>
            TIPO DE SUGERENCIA
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdTiposugNavigation.NombreTipoq)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdS" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">REGRESAR</a>
    </form>
</div>

proyectoBuzon/Views/Sugerencias/Details.cshtml
@model proyectoBuzon.Models.Sugerencias

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Sugerencias</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DescripcionS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescripcionS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdClNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdClNavigation.ApellidosCl)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdTiposugNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdTiposugNavigation.NombreTipoq)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdS">Editar</a> |
    <a asp-action="Index">Back to List</a>
</div>

proyectoBuzon/Views/Sugerencias/Edit.cshtml
@model proyectoBuzon.Models.Sugerencias

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}



<h4>Sugerencias</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdS" />
            <div class="form-group">
                <label asp-for="IdCl" class="control-label">Nombre</label>
                <select asp-for="IdCl" readonly="readonly" class="form-control" asp-items="ViewBag.IdCl"></select>
                <span asp-validation-for="IdCl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdTiposug" class="control-label"></label>
                <select asp-for="IdTiposug" readonly="readonly" class="form-control" asp-items="ViewBag.IdTiposug"></select>
                <span asp-validation-for="IdTiposug" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescripcionS" class="control-label">Descripcion</label>
                <input asp-for="DescripcionS" class="form-control" />
                <span asp-validation-for="DescripcionS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaS" class="control-label"></label>
                <input asp-for="FechaS" readonly="readonly" class="form-control" />
                <span asp-validation-for="FechaS" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="GUARDAR" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">REGRESAR</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

proyectoBuzon/Views/Sugerencias/Index.cshtml
@model IEnumerable<proyectoBuzon.Models.Sugerencias>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Cliente.cshtml";
}


<center>
    <h2>SUGERENCIAS CLIENTE</h2>
</center>

@*<td>
        @Html.ActionLink("<< ATRAS", "IndexSolucionadas", "Quejas", null, new { @class = "btn btn-success btn-lg" })
    </td>*@

<p>

</p>
@*<p>
        <a asp-action="Create">NUEVA SUGERENCIA</a>
    </p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                FECHA
            </th>
            <th>
                CLIENTE
            </th>
            <th>
                TIPO DE SUGERENCIA
            </th>
            <th>
                DESCRIPCIÓN
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaS)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdClNavigation.ApellidosCl)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdTiposugNavigation.NombreTipoq)

                </td>
                <td>

                    @Html.DisplayFor(modelItem => item.DescripcionS)
                </td>
                <td>
                    <a class="btn btn-info btn-sm" asp-action="Edit" asp-route-id="@item.IdS">Editar</a> |
                    @*<a asp-action="Details" asp-route-id="@item.IdS">Details</a> |*@
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.IdS">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<td>
    @Html.ActionLink("<< ATRAS", "Create", "Sugerencias", null, new { @class = "btn btn-success " })
</td>

proyectoBuzon/Views/Sugerencias/IndexAdmin.cshtml
@model IEnumerable<proyectoBuzon.Models.Sugerencias>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_AdminSuge.cshtml";
}

<link rel="stylesheet" href="https://maxcdn.boostrapcdn.com/boostrap/3.3.1/css/boostrap.min.css">

<center>
    <h2>LISTADO DE SUGERENCIAS</h2>
</center>



@*<td>
        @Html.ActionLink("<< ATRAS", "IndexSolucionadas", "Quejas", null, new { @class = "btn btn-success btn-lg" })
    </td>*@

<div class="container">
    <div class="table-responsive">


        @*<p>
            <a asp-action="Create">NUEVA SUGERENCIA</a>
        </p>*@
        <table class="table table-striped table-bordered table-hover ">
            <thead>
                <tr class="info">

                    <th>
                        CLIENTE
                    </th>
                    <th>
                        TIPO DE SUGERENCIA
                    </th>
                    <th>
                        DESCRIPCIÓN
                    </th>
                    <th>
                        FECHA
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>

                        <td>
                            @Html.DisplayFor(modelItem => item.IdClNavigation.ApellidosCl)

                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdTiposugNavigation.NombreTipoq)

                        </td>
                        <td>

                            @Html.DisplayFor(modelItem => item.DescripcionS)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FechaS)

                        </td>
                        @*<td>
                            <a asp-action="Edit" asp-route-id="@item.IdS">Editar</a> |
                            <a asp-action="Details" asp-route-id="@item.IdS">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.IdS">Eliminar</a>
                        </td>*@
                    </tr>
                }
            </tbody>
        </table>
        <P>
            @Html.ActionLink("<< ATRAS", "Index", "Admin", null, new { @class = "btn btn-success btn-lg" })
        </P>
    </div>
</div>